name: CI

on: [push]

jobs:
  test-dotnet:
    name: Test dotnet
    defaults:
      run:
        working-directory: dotnet
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [6.0.x]
        os: [ubuntu-latest]
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up .Net Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build solution
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore
  lint-js-2020:
    name: Lint js/2020
    defaults:
      run:
        working-directory: js/2020
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
  test-js-2020:
    name: Test js/2020
    defaults:
      run:
        working-directory: js/2020
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: yarn test
