name: CI

on: [push]

jobs:
  lint-js-2020:
    name: Lint js/2020
    defaults:
      run:
        working-directory: js/2020
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: yarn lint
  test-js-2020:
    name: Test js/2020
    defaults:
      run:
        working-directory: js/2020
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: yarn test
